# Generated by Django 4.2.8 on 2023-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_born', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('freelance', models.BooleanField()),
                ('address_web', models.CharField(max_length=50)),
                ('degree_of_education', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
            ],
        ),
    ]
